[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NIXPACKS_NODE_VERSION = "20"

