[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.setup.nixPkgsArchive]
# This archive contains Node.js 20.19+
archive = "5148520bfab61f99fd25fb9ff7bfbb50dad3c9db"

[phases.install]
cmds = [
  "npm install --legacy-peer-deps --no-audit --no-fund",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm run start:prod"

[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NODE_VERSION = "20.19.0"

